config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout",
    password: "passwords",
    confirmations: "confirmations"
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :checkouts,  only: [:new, :create, :show, :index]

  # get   "login",  to: "devise/sessions#new"
  # get   "logout", to: "devise/sessions#destroy"

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkout.rb
class Checkout < ApplicationRecord
  def self.log_transaction!(transaction, params)
    checkout = new(params)
    checkout.braintree_id = transaction.id
    checkout.status       = transaction.status
    checkout.save!
  end

  def full_name
    first_name + " " + last_name rescue ""
  end

  def full_address
    return address1 unless address2.present?
    address1 + ", " + address2
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  TRANSACTION_SUCCESS_STATUSES = [
    Braintree::Transaction::Status::Authorizing,
    Braintree::Transaction::Status::Authorized,
    Braintree::Transaction::Status::Settled,
    Braintree::Transaction::Status::SettlementConfirmed,
    Braintree::Transaction::Status::SettlementPending,
    Braintree::Transaction::Status::Settling,
    Braintree::Transaction::Status::SubmittedForSettlement,
  ]

  def new
    @client_token = gateway.client_token.generate
    @price = 9.99
    @total = 9.99
  end

  def show
    @transaction = gateway.transaction.find(params[:id])
    @checkout = Checkout.find_by_braintree_id(params[:id])
    @result = _create_result_hash(@transaction)
  end

  def index
    @checkouts = Checkout.all
  end

  def create
    amount = params["qty"].to_f * 9.99 # In production you should not take amounts directly from clients
    nonce = params["payment_method_nonce"]

    result = gateway.transaction.sale(
      amount: amount,
      payment_method_nonce: nonce,
      :options => {
        :submit_for_settlement => true
      }
    )

    if result.success? || result.transaction
      @checkout = Checkout.log_transaction!(result.transaction, checkout_params)
      redirect_to checkout_path(result.transaction.id)
    else
      error_messages = result.errors.map { |error| "Error: #{error.code}: #{error.message}" }
      flash[:error] = error_messages
      redirect_to new_checkout_path
    end
  end

  def _create_result_hash(transaction)
    status = transaction.status

    if TRANSACTION_SUCCESS_STATUSES.include? status
      result_hash = {
        header: "Sweet Success!",
        icon: "check",
        success: true,
        message: "Thank you for purchasing Fulfillment of Love. Please check your email (#{@checkout.email}) for payment confirmation as well as shipping updates."
      }
    else
      result_hash = {
        header: "Processing Error",
        icon: "times",
        success: false,
        message: "We were unable to process your transaction. Please return to the checkout page and try again."
      }
    end
  end

  def gateway
    @gateway ||= Braintree::Gateway.new(
      environment: Braintree::Configuration.environment,
      merchant_id: Braintree::Configuration.merchant_id,
      public_key: Braintree::Configuration.public_key,
      private_key: Braintree::Configuration.private_key
    )
  end

  private

  def checkout_params
    request.parameters.slice(:email, :first_name, :last_name, :address1, :address2, :city, :state, :zipcode)
  end
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_string(alert)
    alert.is_a?(Array) ? safe_join(alert, "<br />".html_safe) : alert
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/checkouts/index.html.slim
.container
  .row
    .col-sm-12
      section#transactions
        table.table
          thead.thead-dark
            tr
              th ID
              th Date
              th Status
              th Name
              th Email
              th Address
              th City
              th State
              th Zipcode
          tbody
            - @checkouts.each do |checkout|
              tr
                td= checkout.braintree_id
                td= checkout.created_at.strftime("%m/%d/%Y %I:%M %p")
                td= checkout.status
                td= checkout.full_name
                td= checkout.email
                td= checkout.full_address
                td= checkout.city
                td= checkout.state
                td= checkout.zipcode

app/views/checkouts/new.html.slim
section#checkout
  .container
    .row
      .col-sm-8.col-sm-offset-2
        h2 Checkout
        = form_tag "/checkouts", method: :post, id: "payment-form" do
          table.table
            thead.thead-dark
              tr
                th.text-center QTY
                th Description
                th.text-right Price
                th.text-right Total
            tbody
              tr
                td.text-center
                  select#qty.form-control name="qty" required="required"
                    option value="1" 1
                    option value="2" 2
                    option value="3" 3
                    option value="4" 4
                    option value="5" 5
                    option value="6" 6
                    option value="7" 7
                    option value="8" 8
                    option value="9" 9
                    option value="10" 10
                td#description
                  span Special Edition Box Set
                td
                  input#price.form-control.text-right name="price" type="number" value="#{ @price }" readonly="readonly"
                td
                  input#total.form-control.text-right name="total" type="number" value="#{ @total }" readonly="readonly"
          input type="hidden" id="nonce" name="payment_method_nonce"

          h3 Payment Information
          .bt-drop-in-wrapper
            #bt-dropin

          h3 Shipping Information
          .row
            .col-sm-6
              .form-group
                input#firstName.form-control name="first_name" type="string" aria-describedby="firstName" placeholder="First Name" required="required"
            .col-sm-6
              .form-group
                input#lastName.form-control name="last_name" type="string" aria-describedby="lastName" placeholder="Last Name" required="required"
          .row
            .col-sm-12
              .form-group
                input#email.form-control name="email" type="email" aria-describedby="email" placeholder="michael@fulfillmentoflove.com" required="required"
          .row
            .col-sm-12
              .form-group
                input#address1.form-control name="address1" placeholder=("Street address, P.O. box, company name, c/o") type="string" required="required"
          .row
            .col-sm-12
              .form-group
                input#address2.form-control name="address2" placeholder=("Apartment, suite , unit, building, floor, etc.") type="string"
          .row
            .col-sm-4
              .form-group
                input#city.form-control type="string" name="city" aria-describedby="city" placeholder="City" required="required"
            .col-sm-4
              .form-group
                select#state.form-control name="state" required="required"
                  option selected="selected" value=""  Select a State
                  option value="AL"  Alabama
                  option value="AK"  Alaska
                  option value="AZ"  Arizona
                  option value="AR"  Arkansas
                  option value="CA"  California
                  option value="CO"  Colorado
                  option value="CT"  Connecticut
                  option value="DE"  Delaware
                  option value="DC"  District Of Columbia
                  option value="FL"  Florida
                  option value="GA"  Georgia
                  option value="HI"  Hawaii
                  option value="ID"  Idaho
                  option value="IL"  Illinois
                  option value="IN"  Indiana
                  option value="IA"  Iowa
                  option value="KS"  Kansas
                  option value="KY"  Kentucky
                  option value="LA"  Louisiana
                  option value="ME"  Maine
                  option value="MD"  Maryland
                  option value="MA"  Massachusetts
                  option value="MI"  Michigan
                  option value="MN"  Minnesota
                  option value="MS"  Mississippi
                  option value="MO"  Missouri
                  option value="MT"  Montana
                  option value="NE"  Nebraska
                  option value="NV"  Nevada
                  option value="NH"  New Hampshire
                  option value="NJ"  New Jersey
                  option value="NM"  New Mexico
                  option value="NY"  New York
                  option value="NC"  North Carolina
                  option value="ND"  North Dakota
                  option value="OH"  Ohio
                  option value="OK"  Oklahoma
                  option value="OR"  Oregon
                  option value="PA"  Pennsylvania
                  option value="RI"  Rhode Island
                  option value="SC"  South Carolina
                  option value="SD"  South Dakota
                  option value="TN"  Tennessee
                  option value="TX"  Texas
                  option value="UT"  Utah
                  option value="VT"  Vermont
                  option value="VA"  Virginia
                  option value="WA"  Washington
                  option value="WV"  West Virginia
                  option value="WI"  Wisconsin
                  option value="WY"  Wyoming
            .col-sm-4
              .form-group
                input#zipcode.form-control type="string" name="zipcode" aria-describedby="zipcode" placeholder="Zip Code" required="required"
          button#submitBtn.btn.btn-default.pull-right type="submit" Checkout

javascript:
  $(document).on('turbolinks:load', function(){
    var form         = document.getElementById('payment-form');
    var firstName    = document.getElementById('firstName');
    var lastName     = document.getElementById('lastName');
    var addressLine1 = document.getElementById('address1');
    var addressLine2 = document.getElementById('address2');
    var city         = document.getElementById('city');
    var state        = document.getElementById('state');
    var zipcode      = document.getElementById('zipcode');
    var submitBtn    = document.getElementById('submitBtn');
    var client_token = "#{ @client_token }"

    var fields = [
      firstName,
      lastName,
      addressLine1,
      addressLine2,
      city,
      state,
      zipcode,
    ]

    var valid = false

    var qty   = document.getElementById('qty');
    var price = document.getElementById('price');
    var total = document.getElementById('total');

    $("#qty").on('change', function(event){
      console.log("THis fired");
      total.value = event.target.value * price.value
    });

    function validateForm() {
      for (var i = 0; i < fields.length; i++) {
        var field = fields[i]
        if (field.checkValidity()) {
          field.parentNode.classList.add("has-success")
        } else {
          field.parentNode.classList.add("has-error")
        }
      }

      if (!valid){
        submitBtn.disabled = true
      }
    }

    braintree.dropin.create({
      authorization: client_token,
      container: '#bt-dropin',
      paypal: {
        flow: 'checkout',
        amount: total.value,
        currency: 'USD'
      }
    }, function (createErr, instance) {
      form.addEventListener('submit', function (event) {
        event.preventDefault();

        validateForm();

        instance.requestPaymentMethod(function (err, payload) {
          if (err) {
            console.log('Error', err);
            return;
          }

          // Add the nonce to the form and submit
          document.querySelector('#nonce').value = payload.nonce;
          form.submit();
        });
      });
    });
  });

app/views/checkouts/show.html.slim
.container
  .row
    .col-sm-8.col-sm-offset-2
      section#confirmation
        .text-center
          - if @result
            .icon
              i.fa.fa-5x class="fa-#{ @result[:icon] }-circle"
            h1= @result[:header]
            p= @result[:message]
            .mt-3
              - if @result[:success]
                = link_to root_path, class: "btn btn-default" do
                  i.fa.fa-home.pr-2
                  | Return Home
              - else
                = link_to :back, class: "btn btn-default" do
                  i.fa.fa-arrow-left.pr-2
                  | Back
          - else
            section
              p= "Thank you for purchasing Fulfillment of Love. Please check your email (#{@checkout.email}) for payment confirmation as well as shipping updates."
              .mt-3
                = link_to root_path, class: "btn btn-default" do
                  i.fa.fa-home.pr-2
                  | Return Home

app/views/layouts/_navigation.html.slim
nav#topNav.navbar.navbar-default.navbar-fixed-top
  .container
    - if current_page?(root_path)
      .navbar-header
        button.navbar-toggle.collapsed data-target="#bs-navbar" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand.page-scroll href="#first"
          i.fa.fa-heart
      #bs-navbar.navbar-collapse.collapse
        ul.nav.navbar-nav
          li
            a.page-scroll href="#one"  Info
          li
            a.page-scroll href="#two"  Bio
          li
            a.page-scroll href="#three"  Package
          li
            a.page-scroll href="#four"  Store
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#"
                = "Welcome, Michael!"
                span class="caret"
              ul class="dropdown-menu"
                li= link_to "All Purchases", checkouts_path
                li= link_to "Logout", destroy_user_session_path, method: :delete
          - else
            li
              = link_to "Buy", new_checkout_path, class: "page-scroll"
    - else
      .navbar-header
        button.navbar-toggle.collapsed data-target="#bs-navbar" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to root_path + "#first", class: "navbar-brand page-scroll" do
          i.fa.fa-heart
      #bs-navbar.navbar-collapse.collapse
        ul.nav.navbar-nav
          li
            = link_to "Info", root_path + "#one", class: "page-scroll"
          li
            = link_to "Bio", root_path + "#two", class: "page-scroll"
          li
            = link_to "Package", root_path + "#three", class: "page-scroll"
          li
            = link_to "Store", root_path + "#four", class: "page-scroll"
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown" data-target="#" aria-haspopup="true" aria-expanded="false"
                = "Welcome, Michael!"
                span class="caret"
              ul class="dropdown-menu"
                li= link_to "All Purchases", checkouts_path
                li= link_to "Logout", destroy_user_session_path, method: :delete
          - else
            li
              = link_to "Buy", new_checkout_path, class: "page-scroll"

app/views/layouts/application.html.slim
doctype html
html
  head
    title= meta_title
    meta content="width=device-width, initial-scale=1.0" name="viewport"

    = csrf_meta_tags
    = csp_meta_tag

    meta name="meta_title" content="#{meta_title}"
    meta name="description" content="#{meta_description}"

    / Facebook Open Graph data
    meta property="og:title" content="#{meta_title}"
    meta property="og:type" content="website"
    meta property="og:url" content="#{request.original_url}"
    meta property="og:image" content="#{meta_image}"
    meta property="og:description" content="#{meta_description}"
    meta property="og:site_name" content="#{meta_title}"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_path('favicon.png'), rel: 'icon', type: 'image/png'

  body
    = render "layouts/navigation"

    - if flash[:error]
      .alert.alert-danger.alert-dismissible.fade.show
        = alert_string(flash[:error])
        button type="button" class="close" data-dismiss="alert" aria-label="Close"
          span aria-hidden="true">&times;

    = yield
    script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"
    script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"
    script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js"
    script src="https://js.braintreegateway.com/web/dropin/1.15.0/js/dropin.min.js"
    = javascript_include_tag "scripts.js"

app/views/pages/_carousel.html.slim
#header-carousel.carousel.slide data-ride="carousel"
  /! Indicators
  ol.carousel-indicators
    li.active data-slide-to="0" data-target="#header-carousel"
    li data-slide-to="1" data-target="#header-carousel"
    li data-slide-to="2" data-target="#header-carousel"
  /! Wrapper for slides
  .carousel-inner.text-center role="listbox"
    .item.active
      = image_tag("main_bg.png", alt: "Main", class: "w-100")
    .item
      = image_tag("banner-1.jpg", alt: "Second", class: "w-100")
    .item
      = image_tag("banner-2.jpg", alt: "Third", class: "w-100")
  /! Controls
  a.left.carousel-control data-slide="prev" href="#header-carousel" role="button"
    span.glyphicon.glyphicon-chevron-left aria-hidden="true"
    span.sr-only Previous
  a.right.carousel-control data-slide="next" href="#header-carousel" role="button"
    span.glyphicon.glyphicon-chevron-right aria-hidden="true"
    span.sr-only Next

app/views/pages/home.html.slim
= render "carousel"
section#one.bg-primary
  .container
    .row
      .col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-2.text-center
        h2.margin-top-0.text-primary Fulfillment of Love
        br
        p.text-faded
          | This book and 9 track CD is about the declaration of love, which will cover all sensitive questions and give answers to issues like commitment, romance, insecurity, finance, infidelity, health, hygiene and online dating. Because, only the one you love the most can be the one to hurt you the most. It seeks to will inform and educate the reader on the essential factors to consider in to secure a gratifying relationship.
        a.btn.btn-default.btn-xl.page-scroll href="#three"  Explore
section#two
  .container
    .row
      .col-lg-12.text-center
        h2.margin-top-0.text-primary.author-hd About the author
        hr.primary/
      .col-lg-4.col-md-4.text-center
        .feature
          = image_tag("michael_langdon.png", class: "author-img wow fadeInUp", "data-wow-delay": ".2s")
      .col-lg-8.col-md-8
        .feature
          i.icon-lg.ion-android-laptop.wow.fadeIn data-wow-delay=".3s"
          h3 Michael Langdon
          p.text-muted
            | Fulfillment of love is a declaration of love which will ensure the union of love between you and your significant other. True love is a deep and inner feeling which was ordained by God. Scholars, professional artists in all fields of art, sculptors, painters, composers, musicians, singers etc., for hundreds of years and still trying to perfect the word love. As a writer I am fascinated by the word love, there is so many breakups and less making up. But every second there is someone falling in love. Love will be to the existent of time. This book and 9 track CD combination will be the perfect gift for weddings, anniversaries, engagements, beginning of a relationship, or reconciling a relationship. It's a master piece.
section#three.bg-primary
  .container
    .row
      .col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-2.text-center
        h2.text-center.text-primary Package
        p.text-faded
          | The book is available for digital download of both the paperback and audio book. There is also a limited edition package which includes a physical copy of the paperback, along with the audio book presented in a special edition DVD case complete with the audio CD. Below is a preview from the audio book.
        = audio_tag("preview.ogg", "preview.mp3")
section#four.bg-dark
  h2.text-center.text-primary Store
  ul.list-inline.shop-items.text-center
    li.list-inline-item.shop-item
      = image_tag("digital.jpg", class: "img-responsive")
      a.btn.btn-default.buy-button href="https://www.amazon.com/dp/B07MJY2W8M"  E-book ($2.99)
    li.list-inline-item.shop-item
      = image_tag("hardcopy.jpg", class: "img-responsive")
      = link_to "Special Edition Box Set ($9.99)", new_checkout_path, class: "btn btn-default buy-button"
footer#footer
  .container-fluid
    .row
      .col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-2.text-center
        ul.list-unstyled.social-networks
          li
            a href="https://instagram.com/fulfillmentoflove" title="instagram"
              i.fa.fa-instagram
          li
            a href="https://twitter.com/fulfillmentOfL" title="twitter"
              i.fa.fa-twitter
          li
            a href="mailto:info@fulfillmentoflove.com" title="email"
              i.fa.fa-envelope
        p.mar-top-20 ©2016 Fulfillment of Love

app/views/shared/_footer.html.erb
<!-- Email Footer -->
<tr>
  <td class="<%= "bg-red" if status && @opts[:error] %> <%= "bg-green" if status && @opts[:description]%>">
    <table class="email-footer <%= "bg-red" if status && @opts[:error] %> <%= "bg-green" if status && @opts[:description]%>"
      align="center" width="570" cellpadding="0" cellspacing="0">
      <tr>
        <td align="center" style="padding-bottom:0;padding-right:0;padding-left:0;padding-top:20px;" valign="middle">
          <!--[if gte mso 9]>&nbsp;&nbsp;&nbsp;<![endif]-->
          <span class="sg-image">
            <a href="https://twitter.com/<%= twitter %>" target="_blank"><img alt="Twitter" height="18" src="https://d3q93z57vqho8b.cloudfront.net/internationalweekend/twitter-white.png" style="border-width: 0px; margin-right: 16px; margin-left: 16px; width: 23px; height: 18px;" width="23"></a>
          </span>
          <!--[if gte mso 9]>&nbsp;&nbsp;&nbsp;&nbsp;<![endif]-->
          <span class="sg-image">
            <a href="https://www.instagram.com/<%= ig %>/" target="_blank"><img alt="Instagram" height="18" src="https://d3q93z57vqho8b.cloudfront.net/internationalweekend/ig-white.png" style="border-width: 0px; margin-right: 16px; margin-left: 16px; width: 18px; height: 18px;" width="18"></a>
          </span>
          <!--[if gte mso 9]>&nbsp;&nbsp;&nbsp;&nbsp;<![endif]-->
          <span class="sg-image">
            <a href="https://api.whatsapp.com/send?phone=<%= whatsapp %>" target="_blank"><img alt="WhatsApp" height="18" src="https://d3q93z57vqho8b.cloudfront.net/internationalweekend/whatsapp-white.png" style="border-width: 0px; margin-right: 16px; margin-left: 16px; width: 18px; height: 18px;" width="18"></a>
          </span>
        </td>
      </tr>
      <tr>
        <td class="content-cell" align="center">
          <p class="sub align-center">&copy; <%= Date.today.year %> Fulfillment of Love. All rights reserved.</p>
        </td>
      </tr>
    </table>
  </td>
</tr>

app/views/shared/_header.html.erb
<!-- Email Header -->
<tr>
  <td class="email-masthead <%= "bg-red" if status && @opts[:error] %> <%= "bg-green" if status && @opts[:description] %>">
    <h1 class="align-center color-white <%= @opts[:error] ? "red" : "green" %>"><%= @opts[:error_details] ? @opts[:error_details][:summary].titleize : @opts[:status].titleize %></h1>
    <p class="align-center color-white italic">ID: <%= @opts[:transaction_id].upcase %></p>
  </td>
</tr>